# -*- coding: utf-8 -*-
"""Cross Analysis Market.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176mfrUuBAIlptlMbR-XgM7_M13omK-ij

#                                            CROSS MARKET ANALYSIS

# 1. Crypto Currency Coins
"""

url:"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"

import requests
records=[]
for i in range(1,6):
     url=f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page={i}&sparkline=False"
     response=requests.get(url)
     if response.status_code==200:
         data=response.json()
         records.extend(data)

import pandas as pd
df=pd.DataFrame(records)

df.head()

import pandas as pd

df = pd.DataFrame(records)

df['last_updated'] = pd.to_datetime(df['last_updated'])

df['date'] = df['last_updated'].dt.date

df = df.drop('last_updated', axis=1)

df = df[['id', 'symbol', 'name', 'current_price', 'market_cap', 'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply', 'ath', 'atl', 'date']]

df.head()

df.to_csv("crypto_market_data.csv",index=False)

"""# 2. Top 3 Coins - Historical prices"""

url="https://api.coingecko.com/api/v3/coins/{'coins_id'}/market_chart?vs_currency=inr&days=365"

import requests
records=[]
url=f"https://api.coingecko.com/api/v3/coins/{'coins_id'}/market_chart?vs_currency=inr&days=365"
response=requests.get(url)
response

import requests
records=[]
url=f"https://api.coingecko.com/api/v3/coins/{'coins_id'}/market_chart?vs_currency=inr&days=365"
response=requests.get(url)
data=response.json()
records.extend(data)

import pandas as pd
df=pd.DataFrame(records)

import requests
import pandas as pd

url = f"https://api.coingecko.com/api/v3/coins/markets"

params = {
    "vs_currency": "inr",
    "order": "market_cap_desc",
    "per_page": 250,
    "page": 1,
    "sparkline": False
}

response = requests.get(url, params=params)
data = response.json()

df = pd.DataFrame(data)
df.head()

import requests
from datetime import datetime
import pandas as pd

top_3 = df[df["market_cap_rank"] <= 3]
print(top_3[["id", "market_cap_rank", "current_price"]])
all_data = []

for coin_id in top_3["id"]:
    url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart"
    hist_params = {
         'vs_currency': 'inr',
         'days': 365
    }

    hist_data = requests.get(url, params=hist_params).json()

    if "prices" in hist_data:
        for price in hist_data["prices"]:
            timestamp = price[0]
            price_inr = price[1]

            date = datetime.fromtimestamp(timestamp / 1000).strftime("%Y-%m-%d")

            all_data.append({
                "coin_id": coin_id,
                "date": date,
                "price_inr": price_inr
            })

price_df = pd.DataFrame(all_data)
price_df.head()

display(df)

import pandas as pd
price_df = pd.DataFrame(all_data)
price_df.to_csv("top3_daily_price_1year_inr.csv",index=False)

"""Oil prices (WTI Crude)

# 3. Oil Prices (WTI Crude)
"""

url='https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv'

import pandas as pd
oil_df=pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
oil_df

import pandas as pd
from datetime import datetime

start_date_str = '2020-01-01'
end_date_str = '2026-01-31'

start_date = pd.to_datetime(start_date_str)
end_date = pd.to_datetime(end_date_str)

oil_df['Date'] = pd.to_datetime(oil_df['Date'])

filtered_oil_df = oil_df[(oil_df['Date'] >= start_date) & (oil_df['Date'] <= end_date)]
filtered_oil_df

filtered_oil_df.to_csv('oil_df.csv',index=False)

"""# 4.Stock Prices (Yahoo Finance API)"""

import yfinance as yf
import pandas as pd

# Choose indices
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-01-12"

# Download historical data
stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

import pandas as pd
df=stocks_df['^IXIC'].reset_index()
df.columns=pd.MultiIndex.from_product([['^IXIC'],list(df.columns)])

display(df)

stocks_df['^IXIC'].reset_index().to_csv('IXIC.csv',index=False)

import pandas as pd
df=stocks_df["^GSPC"].reset_index()
df.columns=pd.MultiIndex.from_product([["^GSPC"],list(df.columns)])

display(df)

stocks_df["^GSPC"].reset_index().to_csv('GSPC.csv',index=False)

import pandas as pd
df=stocks_df["^NSEI"].reset_index()
df.columns=pd.MultiIndex.from_product([["^NSEI"],list(df.columns)])

display(df)

stocks_df["^NSEI"].reset_index().to_csv('NSEI.csv',index=False)

import pandas as pd
import glob
import os

df_list = ['IXIC.csv','GSPC.csv','NSEI.csv']

df_list = []

for file in df_list:
    df = pd.read_csv(file)
    df_list.append(df)

import pandas as pd

filenames_to_load = ['IXIC.csv','GSPC.csv','NSEI.csv']

dataframes_to_concat = []

for file_name in filenames_to_load:
    df_temp = pd.read_csv(file_name)
    dataframes_to_concat.append(df_temp)

combined_df = pd.concat(dataframes_to_concat, ignore_index=True)

import pandas as pd
import yfinance as yf

all_stocks_data = []

for ticker_symbol in tickers:

    temp_df = stocks_df[ticker_symbol].copy()
    temp_df = temp_df.reset_index()

    temp_df.columns = [col.lower() for col in temp_df.columns]

    temp_df['ticker'] = ticker_symbol

    if 'adj close' in temp_df.columns:
        temp_df = temp_df.drop(columns=['adj close'])

    all_stocks_data.append(temp_df)

df_final_stocks = pd.concat(all_stocks_data, ignore_index=True)

sql_columns = ['date', 'open', 'high', 'low', 'close', 'volume', 'ticker']
df_final_stocks = df_final_stocks[sql_columns]

display(df_final_stocks.head())

df = df_final_stocks

combined_df.to_csv("combined_file.csv", index=False)

"""# Connect to DataFrame into SQL"""

import sqlite3

import sqlite3
import pandas as pd
conn = sqlite3.connect('Market.db')
print("Connected to in-memory database")

import pandas as pd
df=pd.read_csv("crypto_market_data.csv")

"""# 1.Cryptocurrencies Table created"""

cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS Cryptocurrencies (
       id VARCHAR(50) PRIMARY KEY, ---- Unique ID from CoinGecko (e.g., “bitcoin”)
       symbol VARCHAR(50), ---Short symbol (e.g., BTC, ETH)
       name  VARCHAR(100), ---Full name of the cryptocurrency
       current_price DECIMAL(18, 6), --Current trading price INR
       market_cap BIGINT, ----Market capitalization (INR)
       market_cap_rank INT, ---Rank by market capitalization
       total_volume BIGINT, ---Trading volume (24h, INR)
       circulating_supply DECIMAL(20, 6), ---Coins in circulation
       total_supply DECIMAL(20, 6), ---Total supply (if available)
       ath DECIMAL(18, 6), ----All-time high price (INR)
       atl DECIMAL(18, 6),---All-time low price (INR)
       date_only DATE ----Last updated
    )
''')

"""# Insert into Table"""

insert_query = """INSERT OR IGNORE INTO Cryptocurrencies(id, symbol, name, current_price, market_cap,
       market_cap_rank, total_volume, circulating_supply, total_supply,
       ath, atl, date) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)"""

for i, row in df.iterrows():
    values = (row['id'],row['symbol'],row['name'],row['current_price'],row['market_cap'],row['market_cap_rank'],
              row['total_volume'],row['circulating_supply'],row['total_supply'],row['ath'],row['atl'],row['date'])
    cursor.execute(insert_query,values)
conn.commit()

"""# Insert After Viewing Values"""

import pandas as pd

cursor.execute("select * from Cryptocurrencies")
rows = cursor.fetchall()
columns = [i[0] for i in cursor.description]
df = pd.DataFrame(rows,columns=columns)
df.head()

df.isnull().sum()

df.dropna(inplace=True)

pd.read_sql(
    "SELECT count(*) as total_rows FROM Cryptocurrencies ",
    conn
)

"""# 2. Crypto_prices Table Created"""

cursor.execute('''
    CREATE TABLE top3_daily_price_1year_inr(
      coin_id TEXT VARCHAR(50),-----  FOREIGN KEY (coin_id) REFERENCES Cryptocurrencies (id)
      date DATE,
      price_inr DECIMAL(18, 6)

   )
''')

"""# Insert into Table"""

insert_query = """INSERT INTO top3_daily_price_1year_inr (coin_id ,date,price_inr) VALUES (?,?,?)"""

for i, row in df.iterrows():
    values = (row['coin_id'],row['date'],row['price_inr'])
    cursor.execute(insert_query,values)
conn.commit()

df.isnull().sum()

df.dropna(inplace=True)

pd.read_sql(
    "SELECT count(*)as total_rows FROM top3_daily_price_1year_inr ", conn)

"""# Insert After Viewing Values"""

import pandas as pd

cursor.execute("select * from top3_daily_price_1year_inr")
rows = cursor.fetchall()
columns = [i[0] for i in cursor.description]
df = pd.DataFrame(rows,columns=columns)
df.head()

"""3.OIL _ PRICES"""

import pandas as pd
df=pd.read_csv("/content/oil_df.csv")
df.head()

"""# 3. Oil_Prices Table Created"""

cursor.execute('''
    CREATE TABLE oil_prices(
       date DATE PRIMARY KEY,
      price_inr DECIMAL(18, 6) -- WTI crude oil price per barrel (INR)
   )
''')

conn.commit()

"""# Insert into Table"""

insert_query = """INSERT or ignore INTO oil_prices (date,price_inr) VALUES (?,?)"""

for i, row in df.iterrows():
    values = (row['Date'],row['Price'])
    cursor.execute(insert_query,values)
conn.commit()

df.isnull().sum()

"""# Insert After Viewing Values"""

import pandas as pd
cursor.execute("select * from oil_prices")
rows = cursor.fetchall()
columns = [i[0] for i in cursor.description]
df = pd.DataFrame(rows,columns=columns)
df.head()

"""# 4. Stock _ Prices Table Created"""

df.to_csv("stock_prices.csv",index=False)

import pandas as pd
df=pd.read_csv("/content/stock_prices.csv")
df.head()

df.isnull().sum()

df['date'] = pd.to_datetime(df['date'])
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

df.dropna(inplace=True)

cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE stock_prices(
      date DATE,---Trading date
      open decimal(18,6),-----Opening price
      high decimal(18,6),----Highest price of the day
      low decimal(18,6),----Lowest price of the day
      close decimal,----Closing price
      volume bigint,----Trading volume
      ticker varchar(20)---Stock index symbol (e.g., ^GSPC, ^IXIC)


   )
''')

"""# Insert into Table"""

df = df_final_stocks

df.dropna(inplace=True)

df['date'] = pd.to_datetime(df['date'])
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

insert_query = """INSERT or ignore INTO stock_prices (date,open,high,low,close,volume,ticker) VALUES (?,?,?,?,?,?,?)"""

for i, row in df.iterrows():
    values = (row['date'],row['open'],row['high'],row['low'],row['close'],row['volume'],row['ticker'])
    cursor.execute(insert_query,values)
conn.commit()

"""# Insert After Viewing Values"""

import pandas as pd
cursor.execute("select * from stock_prices")
rows = cursor.fetchall()
columns = [i[0] for i in cursor.description]
df = pd.DataFrame(rows,columns=columns)
df.head()

df['ticker'].value_counts()

df.to_csv("stock_prices.csv",index=False)

"""# SQL Queries

# Cryptocurrencies - (1 to 5)

# 1.Find the highest oil price in the last 5 years.
"""

import pandas as pd
pd.read_sql("""SELECT name, market_cap
    FROM Cryptocurrencies
    ORDER BY market_cap DESC
    LIMIT 3;""", conn)

"""# 2.Get the average oil price per year."""

pd.read_sql("""SELECT
   id,symbol,name,circulating_supply,total_supply,
   ROUND((circulating_supply * 100.0) / total_supply, 2) AS supply_percentage
   FROM Cryptocurrencies
   WHERE total_supply IS NOT NULL
   AND total_supply > 0
   AND circulating_supply >= 0.9 * total_supply
   ORDER BY supply_percentage DESC;
   """,conn)

"""# 3.Show oil prices during COVID crash (March–April 2020)."""

pd.read_sql("""SELECT
    id,symbol,name,current_price,ath,
    ROUND((current_price / ath) * 100, 2) AS percent_of_ath
    FROM Cryptocurrencies
    WHERE ath IS NOT NULL
    AND ath > 0
    AND current_price >= 0.9 * ath
    ORDER BY percent_of_ath DESC;
    """, conn)

"""# 4.Find the lowest price of oil in the last 10 years."""

pd.read_sql("""SELECT
ROUND(AVG(market_cap_rank), 2) AS avg_market_cap_rank
FROM Cryptocurrencies
WHERE total_volume >= 1000000000
AND market_cap_rank IS NOT NULL;
""", conn)

"""# 5.Calculate the volatility of oil prices (max-min difference per year)."""

pd.read_sql("""SELECT
id,symbol,name,date
FROM Cryptocurrencies
ORDER BY date DESC
LIMIT 5;
  """,conn    )

"""# Crypto_prices (daily prices of top coins - (6 - 10)

# 6.Find the highest daily price of Bitcoin in the last 365 days.
"""

pd.read_sql("""SELECT
coin_id, MAX(price_inr) AS highest_price_last_365_days
FROM top3_daily_price_1year_inr
WHERE coin_id = 'bitcoin'
AND date >= DATE('now', '-365 day');
""", conn)

"""# 7.Calculate the average daily price of Ethereum in the past 1 year."""

pd.read_sql("""Select
  avg(price_inr)as avg_price_last_365_days
  from top3_daily_price_1year_inr
  where coin_id = 'ethereum'
  and date >= DATE('now', '-366 day');
  """,conn)

"""# 8.Show the daily price trend of Bitcoin in January 2025."""

pd.read_sql("""Select
 date,coin_id,price_inr
 from top3_daily_price_1year_inr
 where coin_id = 'bitcoin'
 and date between '2025-01-01' and '2025-12-31'
 order by date;
 """,conn)

"""# 9.Find the coin with the highest average price over 1 year."""

pd.read_sql("""Select
 coin_id, avg(price_inr)as avg_price
 from top3_daily_price_1year_inr
 group by coin_id
 order by avg_price desc
 limit 1;
 """,conn)

"""# 10.Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025."""

pd.read_sql("""SELECT
  ((MAX(price_inr) - MIN(price_inr)) / MIN(price_inr)) * 100 AS pct_change
   FROM top3_daily_price_1year_inr
   WHERE coin_id='bitcoin'
   AND date BETWEEN '2025-01-27' AND '2026-01-26';
   """, conn)

"""# Oil_prices (11 -15)

# 11.Find the highest oil price in the last 5 years.
"""

pd.read_sql("""Select
  max(price_inr) as highest_price from oil_prices
  where date >= DATE('now', '-5 years');
  """,conn)

"""# 12.Get the average oil price per year."""

pd.read_sql("""SELECT
  strftime('%Y', date) AS year,
  ROUND(AVG(price_inr), 2) AS avg_price
  FROM oil_prices
  GROUP BY year
  ORDER BY year;
  """,conn)

"""# 13.Show oil prices during COVID crash (March–April 2020)."""

pd.read_sql("""SELECT
  date,price_inr
  FROM oil_prices
  WHERE date BETWEEN '2020-03-01' AND '2020-04-30'
  ORDER BY date;
  """,conn)

"""# 14.Find the lowest price of oil in the last 10 years."""

pd.read_sql("""Select
   min(price_inr) as lowest_price from oil_prices
   where date >= DATE('now', '-10 years');
   """,conn)

"""# 15.Calculate the volatility of oil prices (max-min difference per year)."""

pd.read_sql("""SELECT
  strftime('%Y', date) AS year,
  MAX(price_inr) AS max_price,
  MIN(price_inr) AS min_price,
  ROUND(MAX(price_inr) - MIN(price_inr), 2) AS volatility
  FROM oil_prices
  GROUP BY year
  ORDER BY year;
  """,conn)

"""# stock_prices - (16 - 20)

# 16.Get all stock prices for a given ticker
"""

pd.read_sql("""
SELECT *
FROM stock_prices
GROUP BY ticker
ORDER BY date;
""",conn)

"""# 17.Find the highest closing price for NASDAQ (^IXIC)"""

pd.read_sql("""
SELECT MAX(close) AS highest_close
FROM stock_prices
WHERE ticker = '^IXIC';
""",conn)

"""# 18.List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)"""

pd.read_sql("""
SELECT date, (high - low) AS price_diff
FROM stock_prices
WHERE ticker = '^GSPC'
ORDER BY price_diff DESC
LIMIT 5;
""",conn)

"""# 19.Get monthly average closing price for each ticker"""

pd.read_sql("""
SELECT
  ticker,
  strftime('%Y-%m', date) AS month,
  AVG(close) AS avg_close
FROM stock_prices
GROUP BY ticker, month
ORDER BY ticker, month;
""",conn)

"""# 20.Get average trading volume of NSEI in 2024"""

pd.read_sql("""
SELECT AVG(volume) AS avg_volume_2024
FROM stock_prices
WHERE ticker = '^NSEI'
  AND date BETWEEN '2024-01-01' AND '2024-12-31';
  """,conn)

"""# Based on 4 tables - (21 - 30)

# 21. Find the Average Bitcoin vs stock volume average price.
"""

pd.read_sql("""Select
coin_id, avg(price_inr)as avg_price,
avg(s.volume) AS avg_stock_volume
from top3_daily_price_1year_inr t
join stock_prices s on t.date = s.date
where coin_id = 'bitcoin'
;""",conn)

"""# 22.Check if oil prices with S&P 500 high (correlation idea). 2025"""

pd.read_sql("""SELECT
avg(o.price_inr) as avg_oil,
avg(s.high) AS avg_stock_high
FROM top3_daily_price_1year_inr t
JOIN oil_prices o ON t.date = o.date
JOIN stock_prices s ON t.date = s.date
WHERE t.date BETWEEN '2025-01-01' AND '2025-12-31';
""",conn)

"""# 23.Find the average price and avgerage low stock price for 2025-2026."""

pd.read_sql("""SELECT
avg(price_inr) as avg_price,
avg(s.low) AS avg_stock_low
FROM top3_daily_price_1year_inr t
JOIN stock_prices s ON t.date = s.date
WHERE t.date BETWEEN '2025-01-01' AND '2026-12-31';
""",conn)

"""# 24.compare the oil price and the average volume stock price between 2020 and 2025."
"""

pd.read_sql("""SELECT
o.date AS oil_date,
avg(o.price_inr) as avg_price,
avg(s.volume) AS avg_stock_volume
FROM oil_prices o
JOIN stock_prices s ON o.date = s.date
WHERE s.date BETWEEN '2020-01-01' AND '2025-12-31';
""",conn)

"""# 25.Retrieve top3 historical prices and stock ticker, volume, and date for stock data between 2024 and 2025."""

pd.read_sql("""SELECT
avg (price_inr) as price_inr,
s.ticker AS stock_ticker,
s.volume AS stock_volume
FROM top3_daily_price_1year_inr t
JOIN stock_prices s ON t.date = s.date
WHERE t.date BETWEEN '2024-01-01' AND '2025-12-31'
ORDER BY t.date;
""",conn)

"""# 26.Find the average close and oil price for the stock ticker 'NSEI' between 2020 and 2025."""

pd.read_sql("""SELECT
 AVG(s.close) AS avg_stock_close,
 AVG(price_inr) AS avg_price
FROM oil_prices o
JOIN stock_prices s ON o.date = s.date
WHERE s.ticker = '^NSEI'
  AND o.date BETWEEN '2020-01-01' AND '2025-12-31';
""",conn)

"""# 27.Compare the monthly average close prices of stock prices with oil prices."""

pd.read_sql("""SELECT
oil_prices.date,  ticker,
strftime('%Y-%m', stock_prices.date) AS month,
AVG(close) AS avg_close
from oil_prices
join stock_prices on oil_prices.date=stock_prices.date
GROUP BY ticker, month
ORDER BY ticker, month;
""",conn)

"""# 28.Find the top 5 stock tickers with the largest price difference between high and low on the same date"""

pd.read_sql("""SELECT
 ticker,
(high - low) AS price_diff
FROM top3_daily_price_1year_inr t
JOIN stock_prices s ON t.date = s.date
WHERE ticker = '^GSPC'
ORDER BY price_diff DESC
LIMIT 5;
""",conn)

"""#29.Find the top 2 tickers and close in stock prices."""

pd.read_sql("""SELECT
 s.ticker AS stock_ticker,
 s.close AS stock_close
FROM stock_prices s
WHERE s.ticker IN ('^NSEI', '^GSPC')
 ORDER BY  s.ticker
 limit 10;
""",conn)

"""# 30.Find the top 5 stock tickers with the highest price difference (calculated as high - low) for the ticker 'GSPC' (S&P 500) from the stock prices table."""

pd.read_sql("""SELECT
 ticker,
(high - low) AS price_diff
FROM stock_prices s
WHERE ticker = '^GSPC'
ORDER BY price_diff DESC
LIMIT 5;
""",conn)

"""# Install streamlit"""

!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

!streamlit run /content/app.py &>/content/logs.txt &

!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import sqlite3
# import pandas as pd
# import datetime as dt
# 
# st.sidebar.title("Navigation")
# 
# menu = st.sidebar.selectbox(
#     "Select a page:",
#     ["Home", "Cross Market Overview", "SQL Query Runner", "Top 3 Crypto Analysis"]
# )
# 
# # -------------------------
# # HOME PAGE
# # -------------------------
# if menu == "Home":
#     st.title("📊 Cross Market Analysis")
#     st.write("Welcome to the Cross Market Analysis Dashboard")
# 
# # -------------------------
# # CROSS MARKET OVERVIEW
# # -------------------------
# elif menu == "Cross Market Overview":
#     st.title("📈 Cross Market Overview")
# 
#     conn = sqlite3.connect("Market.db")
# 
#     st.subheader("Select Date Range")
#     start_date = st.date_input("Start Date", value=pd.to_datetime("2020-01-01"))
#     end_date = st.date_input("End Date", value=pd.to_datetime("today"))
# 
#     btc_q = f"""
#     SELECT date, current_price AS bitcoin_price
#     FROM Cryptocurrencies
#     WHERE date BETWEEN '{start_date.strftime('%Y-%m-%d')}' AND '{end_date.strftime('%Y-%m-%d')}'
#     """
# 
#     oil_q = f"""
#     SELECT date, price_inr AS oil_price
#     FROM oil_prices
#     WHERE date BETWEEN '{start_date.strftime('%Y-%m-%d')}' AND '{end_date.strftime('%Y-%m-%d')}'
#     """
# 
#     sp_q = f"""
#     SELECT date, close AS sp500_close
#     FROM stock_prices
#     WHERE ticker = '^GSPC'
#       AND date BETWEEN '{start_date.strftime('%Y-%m-%d')}' AND '{end_date.strftime('%Y-%m-%d')}'
#     """
# 
#     nifty_q = f"""
#     SELECT date, close AS nifty_close
#     FROM stock_prices
#     WHERE ticker = '^NSEI'
#       AND date BETWEEN '{start_date.strftime('%Y-%m-%d')}' AND '{end_date.strftime('%Y-%m-%d')}'
#     """
# 
#     btc_df = pd.read_sql(btc_q, conn)
#     oil_df = pd.read_sql(oil_q, conn)
#     sp_df = pd.read_sql(sp_q, conn)
#     nifty_df = pd.read_sql(nifty_q, conn)
# 
#     if not btc_df.empty and not oil_df.empty and not sp_df.empty and not nifty_df.empty:
#         col1, col2, col3, col4 = st.columns(4)
#         col1.metric("Bitcoin Avg", round(btc_df["bitcoin_price"].mean(), 2))
#         col2.metric("Oil Avg", round(oil_df["oil_price"].mean(), 2))
#         col3.metric("S&P 500 Avg", round(sp_df["sp500_close"].mean(), 2))
#         col4.metric("NIFTY Avg", round(nifty_df["nifty_close"].mean(), 2))
# 
#         # -------------------------
#         # 📅 Daily Market Snapshot (Separate Date Ranges)
#         # -------------------------
#         st.subheader("📅 Daily Market Snapshot (Separate Date Ranges)")
# 
#         # --- Bitcoin ---
#         st.markdown("### 🪙 Bitcoin Date Range")
#         btc_start = st.date_input("Bitcoin Start Date", dt.date(2026, 1, 29), key="btc_start")
#         btc_end   = st.date_input("Bitcoin End Date", dt.date(2026, 2, 4), key="btc_end")
# 
#         btc_snap = pd.read_sql(f"""
#         SELECT date, current_price AS bitcoin_price
#         FROM Cryptocurrencies
#         WHERE id = 'bitcoin'
#           AND date BETWEEN '{btc_start}' AND '{btc_end}'
#         ORDER BY date;
#         """, conn)
# 
#         st.dataframe(btc_snap, use_container_width=True)
# 
#         # --- Oil ---
#         st.markdown("### 🛢️ Oil Date Range")
#         oil_start = st.date_input("Oil Start Date", dt.date(2020, 1, 2), key="oil_start")
#         oil_end   = st.date_input("Oil End Date", dt.date(2026, 1, 26), key="oil_end")
# 
#         oil_snap = pd.read_sql(f"""
#         SELECT date, price_inr AS oil_price
#         FROM oil_prices
#         WHERE date BETWEEN '{oil_start}' AND '{oil_end}'
#         ORDER BY date;
#         """, conn)
# 
#         st.dataframe(oil_snap, use_container_width=True)
# 
#         # --- NIFTY ---
#         st.markdown("### 📈 NIFTY Date Range")
#         nifty_start = st.date_input("NIFTY Start Date", dt.date(2020, 1, 1), key="nifty_start")
#         nifty_end   = st.date_input("NIFTY End Date", dt.date(2026, 1, 9), key="nifty_end")
# 
#         nifty_snap = pd.read_sql(f"""
#         SELECT date, open, high, low, close, volume
#         FROM stock_prices
#         WHERE ticker = '^NSEI'
#           AND date BETWEEN '{nifty_start}' AND '{nifty_end}'
#         ORDER BY date;
#         """, conn)
# 
#         st.dataframe(nifty_snap, use_container_width=True)
# 
#     else:
#         st.warning("No data available for selected date range.")
# # -------------------------
# # SQL QUERY RUNNER
# # -------------------------
# elif menu == "SQL Query Runner":
#     st.title("🔎 SQL Query Runner")
# 
#     conn = sqlite3.connect("Market.db")
# 
#     queries = {
#        "1. Find the top 3 cryptocurrencies by market cap":
#         "SELECT name, market_cap FROM cryptocurrencies ORDER BY market_cap DESC LIMIT 3;",
# 
#     "2. List all coins where circulating supply exceeds 90% of total supply":
#         "SELECT name, circulating_supply, total_supply FROM cryptocurrencies WHERE circulating_supply >= 0.9 * total_supply;",
# 
#     "3. Get coins that are within 10% of their all-time-high (ATH)":
#         "SELECT name, current_price, ath FROM cryptocurrencies WHERE current_price >= 0.9 * ath;",
# 
#     "4. Find the average market cap rank of coins with volume above 1B":
#         "SELECT AVG(market_cap_rank) AS avg_rank FROM cryptocurrencies WHERE total_volume > 1000000000;",
# 
#     "5. Get the most recently updated coin":
#        "SELECT id,symbol,name,date FROM Cryptocurrencies ORDER BY date DESC LIMIT 1; ",
# 
#     "6.Find the highest daily price of Bitcoin in the last 365 days.":
#     "SELECT coin_id, MAX(price_inr) AS highest_price_last_365_days FROM top3_daily_price_1year_inr WHERE coin_id = 'bitcoin' AND date >= DATE('now', '-365 day');",
# 
#     "7.Calculate the average daily price of Ethereum in the past 1 year.":
#     "Select  avg(price_inr)as avg_price_last_365_days from top3_daily_price_1year_inr where coin_id = 'ethereum' and date >= DATE('now', '-366 day');",
# 
#     "8.Show the daily price trend of Bitcoin in January 2025.":
#     "Select date,coin_id,price_inr  from top3_daily_price_1year_inr  where coin_id = 'bitcoin' and date between '2025-01-01' and '2025-12-31'   order by date;",
# 
#     "9.Find the coin with the highest average price over 1 year.":
#      "Select coin_id, avg(price_inr)as avg_price from top3_daily_price_1year_inr group by coin_id order by avg_price desc limit 1;",
# 
#     "10.Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025.":
#     "SELECT ((MAX(price_inr) - MIN(price_inr)) / MIN(price_inr)) * 100 AS pct_change FROM top3_daily_price_1year_inr WHERE coin_id='bitcoin'AND date BETWEEN '2025-01-27' AND '2026-01-26';",
# 
#     "11.Find the highest oil price in the last 5 years.":
#     "Select max(price_inr) as highest_price from oil_prices where date >= DATE('now', '-5 years');",
#     "12.Get the average oil price per year.":
#     " SELECT strftime('%Y', date) AS year, ROUND(AVG(price_inr), 2) AS avg_price FROM oil_prices GROUP BY year ORDER BY year;",
# 
#    " 13.Show oil prices during COVID crash (March–April 2020).":
#     "SELECT date, price_inr FROM oil_prices WHERE date BETWEEN '2020-03-01' AND '2020-04-30' ORDER BY date;",
# 
#     "14.Find the lowest price of oil in the last 10 years.":
#      "Select min(price_inr) as lowest_price from oil_prices where date >= DATE('now', '-10 years');",
# 
#     "15.Calculate the volatility of oil prices (max-min difference per year).":
#     "SELECT strftime('%Y', date) AS year, MAX(price_inr) AS max_price, MIN(price_inr) AS min_price, ROUND(MAX(price_inr) - MIN(price_inr), 2) AS volatility FROM oil_prices GROUP BY year  ORDER BY year;",
# 
#     "16.Get all stock prices for a given ticker":
#     "SELECT * FROM stock_prices GROUP BY ticker ORDER BY date;",
# 
#     "17.Find the highest closing price for NASDAQ (^IXIC)":
#     "SELECT MAX(close) AS highest_close FROM stock_prices WHERE ticker = '^IXIC';",
# 
#     "18.List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)":
#     "SELECT date, (high - low) AS price_diff FROM stock_prices WHERE ticker = '^GSPC' ORDER BY price_diff;",
# 
#     "19.Get monthly average closing price for each ticker":
#     "SELECT ticker, strftime('%Y-%m', date) AS month, AVG(close) AS avg_close FROM stock_prices GROUP BY ticker, month ORDER BY ticker, month;",
# 
#     "20.Get average trading volume of NSEI in 2024":
#     "SELECT AVG(volume) AS avg_volume_2024 FROM stock_prices WHERE ticker = '^NSEI' AND date BETWEEN '2024-01-01' AND '2024-12-31';",
# 
#     "21. Find the Average Bitcoin vs stock volume average price.":
#     "Select  coin_id, avg(price_inr)as avg_price, avg(s.volume) AS avg_stock_volume from top3_daily_price_1year_inr t join stock_prices s on t.date = s.date where coin_id = 'bitcoin';",
# 
#     "22.Check if oil prices with S&P 500 high (correlation idea). 2025.":
#     "SELECT avg(o.price_inr) as avg_oil, avg(s.high) AS avg_stock_high FROM top3_daily_price_1year_inr t JOIN oil_prices o ON t.date = o.date JOIN stock_prices s ON t.date = s.date WHERE t.date BETWEEN '2025-01-01' AND '2025-12-31';",
# 
#     "23.Find the average price and avgerage low stock price for 2025-2026.":
#     "SELECT avg(price_inr) as avg_price, avg(s.low) AS avg_stock_low FROM top3_daily_price_1year_inr t JOIN stock_prices s ON t.date = s.date WHERE t.date BETWEEN '2025-01-01' AND '2026-12-31';",
# 
#     "24.compare the oil price and the average volume stock price between 2020 and 2025.":
#     "SELECT o.date AS oil_date, avg(o.price_inr) as avg_price, avg(s.volume) AS avg_stock_volume FROM oil_prices o JOIN stock_prices s ON o.date = s.date WHERE s.date BETWEEN '2020-01-01' AND '2025-12-31';",
# 
#     "25.Retrieve top3 historical prices and stock ticker, volume, and date for stock data between 2024 and 2025.":
#     "SELECT avg (price_inr) as price_inr, s.ticker AS stock_ticker, s.volume AS stock_volume FROM top3_daily_price_1year_inr t JOIN stock_prices s ON t.date = s.date WHERE t.date BETWEEN '2024-01-01' AND '2025-12-31' ORDER BY t.date;",
# 
#     "26.Find the average close and oil price for the stock ticker 'NSEI' between 2020 and 2025.":
#     "SELECT AVG(s.close) AS avg_stock_close, AVG(price_inr) AS avg_price FROM oil_prices o JOIN stock_prices s ON o.date = s.date WHERE s.ticker = '^NSEI'   AND o.date BETWEEN '2020-01-01' AND '2025-12-31';",
# 
#     "27.Compare the monthly average close prices of stock prices with oil prices.":
#     "SELECT oil_prices.date,  ticker, strftime('%Y-%m', stock_prices.date) AS month, AVG(close) AS avg_close from oil_prices join stock_prices on oil_prices.date=stock_prices.date GROUP BY ticker, month ORDER BY ticker, month;",
# 
#     "28.Find the top 5 stock tickers with the largest price difference between high and low on the same date":
#     "SELECT ticker,(high - low) AS price_diff FROM top3_daily_price_1year_inr t JOIN stock_prices s ON t.date = s.date WHERE ticker = '^GSPC' ORDER BY price_diff DESC Limit 5;",
# 
#     "29.Find the top 2 tickers and close in stock prices.":
#     "SELECT   s.ticker AS stock_ticker,  s.close AS stock_close FROM stock_prices s  WHERE s.ticker IN ('^NSEI', '^GSPC')  ORDER BY  s.ticker limit 10;",
# 
#     "30.Find the top 5 stock tickers with the highest price difference (calculated as high - low) for the ticker 'GSPC' (S&P 500) from the stock prices table.":
#     "SELECT  ticker, (high - low) AS price_diff FROM stock_prices s WHERE ticker = '^GSPC' ORDER BY price_diff DESC LIMIT 5;"
#     }
# 
#     selected_question = st.selectbox("Select a Question", list(queries.keys()))
#     st.text_area("SQL Query", queries[selected_question], height=80)
# 
#     if st.button("Run Query"):
#         try:
#             df = pd.read_sql(queries[selected_question], conn)
#             st.success("Query executed successfully!")
#             st.dataframe(df)
#         except Exception as e:
#             st.error(f"Error: {e}")
# 
# # -------------------------
# # TOP 3 CRYPTO ANALYSIS
# # -------------------------
# elif menu == "Top 3 Crypto Analysis":
#     st.title("🪙 Top 3 Crypto Analysis")
# 
#     conn = sqlite3.connect("Market.db")
# 
#     coins = {
#         "Bitcoin (BTC)": "bitcoin",
#         "Ethereum (ETH)": "ethereum",
#         "Tether (USDT)": "tether"
#     }
# 
#     selected_coin_name = st.selectbox("Select a Coin", list(coins.keys()))
#     selected_coin = coins[selected_coin_name]
# 
#     col1, col2 = st.columns(2)
#     with col1:
#         start_date = st.date_input("Start date", dt.date(2025, 2, 5))
#     with col2:
#         end_date = st.date_input("End date", dt.date(2026, 2, 4))
# 
#     if st.button("Show Price"):
#         query = """
#         SELECT DISTINCT date, price_inr
#         FROM top3_daily_price_1year_inr
#         WHERE coin_id = ?
#           AND date BETWEEN ? AND ?
#         ORDER BY date ASC
#         """
# 
#         df = pd.read_sql(query, conn, params=(selected_coin, str(start_date), str(end_date)))
# 
#         if df.empty:
#             st.warning("No data found for this period.")
#         else:
#             st.success(f"Daily price for {selected_coin_name}")
#             st.dataframe(df)

!streamlit run /content/app.py &>/content/logs.txt &

!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"